# IOx app needs base-rootfs. Select either 32 or 64 bit version by uncommenting out one of the below link.
# Use below link for 64 bit Access Points
# FROM devhub-docker.cisco.com/iox-docker/ir1101/base-rootfs:latest

# USE below link for 32 bit Access Points
FROM devhub-docker.cisco.com/iox-docker/ap3k/base-rootfs:latest
COPY main /usr/bin/main
RUN export HOST_DEV=/dev/ttyH0
RUN chmod 777 /usr/bin/main
