descriptor-schema-version: "2.10"

info:
  name: Go-based HTTP Poster App
  description: "Go-based HTTP Poster App"
  version: "1.0"
  author-link: "http://www.airistaflow.com"
  author-name: "AiRISTA"

app:
 # Refer Platform Support Matrix table.
 # armv7l for 32 bit CPU Architecture.
 # aarch64 for 64 bit CPU Architecture.
  cpuarch: armv7l
  type: docker # Indicate app type (docker)

  resources:
    profile: c1.small
    devices:
    - type: serial
      label: HOST_DEV
      alias: usb
      usage: serial device of usb dongle connected to ap.
    network:
      - interface-name: eth0
        ports:
            tcp:
            - 80

# Specify runtime and startup
  startup:
    rootfs: rootfs.img
    target: /usr/bin/main 1>/dev/null 2>/dev/null
